Add `parallel` option for cmake
holepunchto/bare-dev pull request #14
Opened 2024-06-25 15:22 UTC by chm-diederichs

2024-06-26 18:03 UTC, kasperisager requested changes

2024-06-26 18:03 UTC, kasperisager commented on bin/bare-dev.js
> +  )
This should be added to the `build` command, not the global command.

2024-06-26 18:06 UTC, chm-diederichs commented on bin/bare-dev.js
> +  )
OK, will do. Shall I also add to the `install` command too?

2024-06-26 18:15 UTC, kasperisager commented on bin/bare-dev.js
> +  )
That'd be great, yep!

2024-06-27 21:15 UTC, kasperisager requested changes
As it currently stands, this will make all builds sequential by default as `--parallel 1` is passed to CMake unless something else is specified. Let's use the number of available cores as the default instead; might as well put them to use!

2024-06-28 09:27 UTC, kasperisager commented
Perfect, that works as well!

2024-06-28 09:28 UTC, kasperisager approved these changes

2024-06-28 10:50 UTC, chm-diederichs commented
> As it currently stands, this will make all builds sequential by default as `--parallel 1` is passed to CMake unless something else is specified. Let's use the number of available cores as the default instead; might as well put them to use!

I think by default cmake builds sequentially, maybe it is better to use `os.availableParallelism()` then, what do you think?

2024-06-28 10:55 UTC, mafintosh commented
i think the normal saturation default is cores + 1 from back in my day

2024-06-28 10:57 UTC, kasperisager commented
The default depends on the build system used. Ninja, for example, will be as parallel as possible unless otherwise specified, whereas MSBuild will be strictly sequential.

2024-06-28 14:52 UTC, chm-diederichs commented
Ok, in which case seems appropriate to defer to the build system default

2024-07-01 07:21 UTC, merged